require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'spec/dummy/**/*'
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.6

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

Lint/HandleExceptions:
  Exclude:
    - 'Rakefile'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/LineLength:
  Max: 170

Rails:
  Enabled: true

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/models/spree/payment_method/bank_transfer.rb'

Style/Documentation:
  Enabled: false
