AllCops:
  Exclude:
    - 'spec/dummy/**/*'
    - 'vendor/bundle/**/*'
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Max: 170

Style/Documentation:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - 'Rakefile'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/models/spree/payment_method/bank_transfer.rb'

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'
